
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-12
owner: ucsb-cs156-s26
repo_name: team01-s26-12
pull_requests: [{"author":{"id":"U_kgDOCu8TgA","is_bot":false,"login":"JayYeung5","name":""},"headRefName":"jy-UCSBDiningCommonsMenuItem-delete","number":63,"title":"Jy ucsb dining commons menu item delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-12/pull/63"},{"author":{"id":"U_kgDOCu8TgA","is_bot":false,"login":"JayYeung5","name":""},"headRefName":"jy-UCSBDiningCommonsMenuItem-put","number":62,"title":"Jy - ucsb dining commons menu item put","url":"https://github.com/ucsb-cs156-s26/team01-s26-12/pull/62"},{"author":{"id":"U_kgDOCu8TgA","is_bot":false,"login":"JayYeung5","name":""},"headRefName":"jy-UCSBDiningCommonsMenu-get","number":60,"title":"Jy ucsb dining commons menu get","url":"https://github.com/ucsb-cs156-s26/team01-s26-12/pull/60"},{"author":{"id":"U_kgDOCu8TgA","is_bot":false,"login":"JayYeung5","name":""},"headRefName":"jy-UCSBDiningCommonsMenuItem-controller","number":59,"title":"jy - ucsb dining commons menu item controller","url":"https://github.com/ucsb-cs156-s26/team01-s26-12/pull/59"},{"author":{"id":"U_kgDOCu8TgA","is_bot":false,"login":"JayYeung5","name":""},"headRefName":"jy-UCSBDiningCommonsMenu-create-database","number":58,"title":"jy - create ucsbdiningcommonsmenuitem database table","url":"https://github.com/ucsb-cs156-s26/team01-s26-12/pull/58"}]
